### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by CarvFS** [calpolyccg/MDSAPT#43]
Hello! First of all: thank you very much for developing this tool!

I am here through [openjournals/issues#5931](https://github.com/openjournals/joss-reviews/issues/5931). I am installing your packaged and I am receiving an error message while running `mdsapt generate test`

```
Traceback (most recent call last):
  File "/home/felipe/miniconda3/envs/mdsapt/bin/mdsapt", line 5, in <module>
    from mdsapt.cli import cli
  File "/home/felipe/miniconda3/envs/mdsapt/lib/python3.9/site-packages/mdsapt/__init__.py", line 8, in <module>
    from .config import Config, load_from_yaml_file
  File "/home/felipe/miniconda3/envs/mdsapt/lib/python3.9/site-packages/mdsapt/config.py", line 132, in <module>
    class RangeFrameSelection(BaseModel):
  File "/home/felipe/miniconda3/envs/mdsapt/lib/python3.9/site-packages/mdsapt/config.py", line 145, in RangeFrameSelection
    @root_validator()
  File "/home/felipe/miniconda3/envs/mdsapt/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

My package versions are:

```
mdanalysis                2.6.1
mdsapt                    2.0.0+1.gffc3bd0
pyyaml                    6.0
pydantic                  2.4.0
```

Should I have other specific versions installed?

Also, I have installed by cloning your repository and then running `pip install ./MDSAPT`.

**Comment by ALescoulie** [comment]
@CarvFS I looked into it and it seems like we need to modify our config validation due to pydantic deprecating `root_validator`. @ifd3f wrote most of config, and is going to get started on it soon.

**Comment by ALescoulie** [comment]
@CarvFS, @ifd3f refactored our code to use a new version of pydantic, one issue was that a Psi4 depenency also used pydantic, but used a legacy version. A change I just merged should fix this issue. I'll make new release today as well

**Comment by CarvFS** [comment]
Thank you very much! I will try installing again later :)

**Comment by CarvFS** [comment]
Sorry about the delay! So, I have tried again and I am still getting errors because of `pydantic`:

```
/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'allow_mutation' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/felipe/miniconda3/envs/mdsapt3/bin/mdsapt", line 5, in <module>
    from mdsapt.cli import cli
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/mdsapt/__init__.py", line 9, in <module>
    from .sapt import TrajectorySAPT, DockingSAPT
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/mdsapt/sapt.py", line 34, in <module>
    import psi4
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/psi4/__init__.py", line 76, in <module>
    from .driver import endorsed_plugins
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/psi4/driver/__init__.py", line 42, in <module>
    from qcelemental import constants
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/qcelemental/__init__.py", line 6, in <module>
    from . import covalent_radii, models, molparse, molutil, periodic_table, physical_constants, util, vanderwaals_radii
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/qcelemental/models/__init__.py", line 10, in <module>
    from .align import AlignmentMill
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/qcelemental/models/align.py", line 6, in <module>
    from ..util import blockwise_contract, blockwise_expand
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/qcelemental/util/__init__.py", line 1, in <module>
    from .autodocs import auto_gen_docs_on_demand, get_base_docs
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/qcelemental/util/autodocs.py", line 6, in <module>
    from pydantic import BaseModel, BaseSettings
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/pydantic/__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/pydantic/_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.
```

As I understood, it seems something being used was moved in the second version of pydantic. I have tried using the first version of pydantic, but I got another error:

```
Traceback (most recent call last):
  File "/home/felipe/miniconda3/envs/mdsapt3/bin/mdsapt", line 5, in <module>
    from mdsapt.cli import cli
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/mdsapt/__init__.py", line 8, in <module>
    from .config import Config, load_from_yaml_file
  File "/home/felipe/miniconda3/envs/mdsapt3/lib/python3.9/site-packages/mdsapt/config.py", line 20, in <module>
    from pydantic import BaseModel, Field, model_validator, \
ImportError: cannot import name 'model_validator' from 'pydantic'
```

If I got it correctly, `model_validator` was added in the second version of pydantic. 

Is there any specific version I should use?

**Comment by wiederm** [comment]
Hello everyone! 

I am here through https://github.com/openjournals/joss-reviews/issues/5931 : 

I tried to install the package using
`mamba install -c psi4/label/dev -c conda-forge mdsapt`
with `python=3.11`, but the packages can't be resolved.

Also, could you please link the installation instructions or the documentation in the `README.md` or the sidebar?

**Comment by ifd3f** [comment]
@CarvFS Did you try reinstalling the environment file with `mamba env update -f environment.yml`? I updated the dependencies. If that doesn't work, try deleting the environment and reinstalling it.

@wiederm The package currently in the psi4 repos is a year out of date. I'm working on publishing the new version right now.

**Comment by CarvFS** [comment]
Hi @ifd3f! Thank you for your reply. I have tried your suggestiong, but I got

```
$ conda env update -f environment.yml
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: \ Killed
```

**Comment by ifd3f** [comment]
Oh, right, the environment is extremely big because of how many dependencies both psi4 and mdsapt both have. Conda often uses lots of memory and runs forever to solve this environment, but mamba is much faster and more reliable.

**Comment by CarvFS** [comment]
I have used `libmamba` solver (`conda env update -f environment.yml --solver=libmamba`) and it worked! Now the code is running, although with the warning:

```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
```

But MDSAPT is running now and the input file was generated as described in the submitted paper :)

**Comment by ALescoulie** [comment]
@CarvFS that's great! Conda has been such a headache this whole project since we have a large environment. Were also working on a conda-forge deployment that should be done this weekend. If you have any other question don't hesitate to ask @ifd3f and I are happy to help. You can follow issue #45 to see the progress on that.
